### PR TITLE
Added opensim-rl environment and a sample configuration and options for a continuous DQN agent to learn in that environment

### PR DESCRIPTION
**Pull request by praveen-palanisamy**
[opensim-rl](https://github.com/stanfordnmbl/osim-rl) Is an environment introduced by the NIPS 2017 Learning to run challenge. In this environment, an agent is tasked with learning how to run while avoiding obstacles on the ground. The environment provides a human musculoskeletal model and a physics-based simulation environment which are pretty good. This environment will be useful for training agents that can handle much more complex control tasks even after the NIPS challenge ends. Can be seen as a good alternative or as a complementary environment to Mujoco based environments.

**Contributions:**
-  [x] [Added the opensim-rl environment as a stand-alone environment into the existing framework](
fcdab5b)
-  [x] [Added sample factory configurations for the opensim-rl environment](7391551)
-  [x] [Added sample options for training a DQN agent in the opensim-rl environment](7391551)
-  [x] [Modified the dqn agent to produce a list of actions instead of an action index so that it can be extended to be used for action dimensions >1](7391551)
-  [x] [Updated README to point to the opensim-rl to set up the dependencies](cd3b9cf)

### CODE REVIEW

**Comment by jingweiz** [comment]
Great! Thanks a lot for the contribution! Sorry just saw :P

**Comment by jingweiz** [comment]
Hey,
I wasn't looking carefully yesterday when I merged your pr. I now have one confusion, you didn't add any "dqn-mlp-con" model in the `core/models/` right? Then the factory would give an error when it tries to parse this option, can you double check it? Thanks a lot!

**Comment by praveen-palanisamy** [comment]
The `dqn-mlp-con` option uses the `DQNMlpModel` class defined in `core/models/dqn_mlp.py` and pointed to the factory via the `ModelDict` in [this line](https://github.com/jingweiz/pytorch-rl/pull/10/commits/73915513d486542cb6b76c1ec14cb47bb2e95310#diff-9c9533631b45255f5e2dd71017790c3fR25) in the `factory.py` file.
So, it does not produce any error.

**Comment by praveen-palanisamy** [comment]
I tried to make sure (again) that the code after the PR runs fine without errors with config option 8 (corresponding to the opensim). The training starts fine with the opensim environment without any issues.

Though, there is a minor change: I had to rename `opensim.py` to `core/ envs/opensim.py`. I will update the  PR with a new commit for the rename. UPDATE: I am not able to update this PR because of the merge/revert. Should I send in a new PR for the rename? ( `opensim.py` to `core/ envs/opensim.py`)

- [x] Double checked the commits in this PR and tested if the DQN agent works/trains with the opensim environment.

**Comment by jingweiz** [comment]
Hey,
thanks a lot for the effort! I think what I'm a little confused about is that the dqn setup can only work with discrete actions, and all the models that are not ended with "-con" means they are for discrete action spaces. So do you meant to use the discrete version? Or are there any misunderstandings?

**Comment by jingweiz** [comment]
Hey,
I think the pr is fine if you just simply don't add that new config, maybe you can try push again your old pr then I can easily modify it? Thanks! And sorry for the trouble!

**Comment by praveen-palanisamy** [comment]
The DQN in this repository (without the Normalized Advantage Function) is not a good config for the opensim environment. Sorry I should have realized that before. I will try to add it later. 
For now, I will do what you suggested: I will submit the PR.

**Pull request merged**
